version: '3.3'
services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'a4'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - 127.0.0.1:3307:3306
    volumes:
      - my-db:/var/lib/mysql
  tomcat:
    build: ./
    environment:
      DATABASE_HOSTNAME: 'db'
      DATABASE_PORT: '3306'
    depends_on:
      - db
    ports:
      - '80:8082'
# Names our volume
volumes:
  my-db:
